<?php 

    // get access to database
include_once "common/base.php";
?>
<!DOCTYPE html>
<html lang="en">

<head>

    <!-- Page title generated by content page -->
    <title>Timewise | <?php echo $pageTitle ?></title>

    <!-- Set character set -->
    <meta charset="utf-8">

    <!-- Ensure proper rendering and touch zooming on different devices -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


    <!-- jQuery library -->
    <script src="libs/jquery-3.3.1-dist/jquery.min.js"></script>
    <!-- Bootstrap CSS and javascript -->
    <link rel="stylesheet" href="libs/bootstrap-3.3.7-dist/css/bootstrap.css">
    <script src=libs/bootstrap-3.3.7-dist/js/bootstrap.js></script> 
    <!-- datepicker css and javascript -->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!-- Timewise stylesheet -->
    <link rel="stylesheet" href="styles/timewise.css" type="text/css">



    
    
</head>

<body style=<?php echo empty($_SESSION['colour']) ? "\"background-image: url('images/mountainpath.jpg');\""  :  "\"background-color:".$_SESSION['colour'].";\"" ?>>




    <header class="container-fluid">
        <div id="menu" class="navbar navbar-default navbar-fixed-top">
            <div class="navbar-header">

                <div id="logo">
                    <a class="navbar-brand" href="#"><img src="images/logo.PNG" id="logo" alt="Timewise" class="img-responsive" ></a>
                    <?php

                    if(isset($_SESSION['loggedin']) && isset($_SESSION['username'])
                        && $_SESSION['loggedin']==1):

                    ?>

                    <button class="btn btn-success navbar-toggle" data-toggle = "collapse" data-target=".navbar-collapse"><span class="glyphicon glyphicon-align-justify"></span></button>
                    <?php
                endif; 
                ?>
            </div>
        </div>

        <?php

        if(isset($_SESSION['loggedin']) && isset($_SESSION['username'])
            && $_SESSION['loggedin']==1):

        ?>



        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a><?php echo $_SESSION['username']; ?></a></li>

                <li class="nav"><a href="planner.php">Planner</a></li>

                <li class="nav"><a href="scripts/php/logout.php">Log out</a></li>

                <li class="nav"><a href="account.php">Your Account</a></li>
            </ul>
        </div>

        <?php
    endif; 
    ?>
</div>
</header>


